# Generated by Django 5.1.1 on 2024-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customer_phone_number_alter_customer_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
